context:
  version: "21.0.1"

package:
  name: relay
  version: ${{ version }}

source:
  url: https://github.com/facebook/relay/archive/v${{ version }}.tar.gz
  sha256: 51ae08625282c62b291273397f22a996534b8c9da8cce420932fae76f552fb82

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - openssl

tests:
  - script:
      - relay --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Relay is a JavaScript framework for building data-driven React applications.
  homepage: https://github.com/facebook/relay
  repository: https://github.com/facebook/relay

extra:
  recipe-maintainers:
    - danielnachun
