context:
  version: "21.0.0"

package:
  name: relay
  version: ${{ version }}

source:
  url: https://github.com/facebook/relay/archive/v${{ version }}.tar.gz
  sha256: 874e2e5419ad4225eabb59c126730f8892d6e273faa8387b0a725693cf5fc7a0

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - openssl

tests:
  - script:
      - relay --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Relay is a JavaScript framework for building data-driven React applications.
  homepage: https://github.com/facebook/relay
  repository: https://github.com/facebook/relay

extra:
  recipe-maintainers:
    - danielnachun
